<?php	
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// CAUTION : THIS FILE IS GENERATED BY spec.amola
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	require_once 'init.php';

	$bShowError = #SHOW_ERROR#;
	if($bShowError){
		ini_set('display_errors', 1);
		ini_set('display_startup_errors', 1);
		error_reporting(E_ALL);
	}
	
	$authRequired = #AUTH_REQUIRED#;

	$resp = array();
	try{

		#DB_CONNECT#

		$conn->begin_transaction();

		#ASSERT#

		#GET_PARAMS#
		
		#PARAM_VALIDATE_CHECK#

		#PARAM_ESCAPE#

		#PARAM_SET_TYPE#

		$names = array();
		$values = array();

		#SET_VALUE_NAME_AND_VALUE_ARRAY#

		
		$query = "INSERT INTO `#TABLE#` (".implode(",", $names).") VALUES(".implode(",", $values).")";
		$num = insert($conn, $query);
		

		$resp["success"] = true;
		$resp["inserted"] = $num;
		
		if($num > 0){
			$resp["insert_id"] = $conn->insert_id;
			
			
			#ON_SUCCESS#
		}

		echo json_encode($resp);
		$conn->commit();

	}catch(Exception $e){
		
		$conn->rollback();    //롤백

		$resp["success"] = false;
		$resp["error"] = $e->getMessage();
		echo json_encode($resp);
	}

	if(empty($conn) == false)
		closeDb($conn);
	
?>
