<?php
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// CAUTION : THIS FILE IS GENERATED BY spec.amola
	////////////////////////////////////////////////////////////////////////////////////////////////////////////

	require_once './common/init.php';

	$bShowError = #SHOW_ERROR#;
	if($bShowError){
		ini_set('display_errors', 1);
		ini_set('display_startup_errors', 1);
		error_reporting(E_ALL);
	}

	$authRequired = #AUTH_REQUIRED#;

	$resp = array();

	try{

		#DB_CONNECT#

		$conn->begin_transaction();

		#ASSERT#
		
		#GET_PARAMS#

		#PARAM_VALIDATE_CHECK#

		#PARAM_ESCAPE#

		#PARAM_SET_TYPE#

		$conditionList = array();
		#SET_CONDITION_LIST#		
		if(count($conditionList)>0)
			$conditionQuery = " WHERE ".implode(" AND ", $conditionList);
		else
			throw new Exception("delete need condtions");


		$selectQuery = "#SELECT_QUERY#".$conditionQuery;
		$originalData = selectOne($conn, $selectQuery);

		$query = "#DELETE_QUERY#".$conditionQuery;
		$removed = delete($conn, $query);

		if($removed > 0){
			#ON_SUCCESS#
		}

		
		$resp["success"] = true;
		$resp["removed"] = $removed;

		$conn->commit();

	}catch(Exception $e){
		
		$conn->rollback();    
		
		$resp["success"] = false;
		$resp["error"] = $e->getMessage();
	}

	echo json_encode($resp);

	
	if(empty($conn) == false)
		closeDb($conn);
	
?>
