<?php
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// CAUTION : THIS FILE IS GENERATED BY spec.amola
	////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	require_once 'init.php';

	$bShowError = #SHOW_ERROR#;
	if($bShowError){
		ini_set('display_errors', 1);
		ini_set('display_startup_errors', 1);
		error_reporting(E_ALL);
	}

	$authRequired = #AUTH_REQUIRED#;
	
	$resp = array();		
	
	try{

		#DB_CONNECT#


		#ASSERT#

		#GET_PARAMS#
		if(array_key_exists('page', $_REQUEST))	$page = $_REQUEST['page'];
		if(array_key_exists('num', $_REQUEST))	$num = $_REQUEST['num'];
		if(array_key_exists('orderBy', $_REQUEST))	$orderBy = $_REQUEST['orderBy'];
		if(array_key_exists('orderByDesc', $_REQUEST))	$orderByDesc = $_REQUEST['orderByDesc'];

		#PARAM_VALIDATE_CHECK#

		#PARAM_ESCAPE#
		

		#PARAM_SET_TYPE#
		if(empty($page)) $page = 0;
		if(empty($num)) $num = 50;
		$offset = $page * $num;


		$conditionList = array();
		#SET_CONDITION_LIST#		
		
		$conditionQuery = "";
		if(count($conditionList)>0)
			$conditionQuery = " WHERE ".implode(" AND ", $conditionList);

		
		$query = "#SELECT_QUERY#".$conditionQuery."#GROUP_BY#";

		if(isset($orderBy))
			$query .= " ORDER BY $orderBy LIMIT $offset,$num";
		else if(isset($orderByDesc))
			$query .= " ORDER BY $orderByDesc DESC LIMIT $offset,$num";
		else
			$query .= " LIMIT $offset,$num";

		$dataList = select($conn, $query);
		if($dataList===null)
			$dataList = array();

		foreach($dataList as &$item){
			unset($item['passwd']);
		}

		$cntQuery = "#TOTAL_COUNT_QUERY#";
		$total = selectNum($conn, $cntQuery);

		closeDb($conn);

		$resp["success"] = true;
		$resp["dataList"] = $dataList;
		$resp["total"] = $total;
		$resp["page"] = $page;
		$resp["num"] = $num;

	}catch(Exception $e){
		$resp["success"] = false;
		$resp["error"] = $e->getMessage();
	}
	
	echo json_encode($resp);
?>
